name: waste2worth
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0" # Ensures compatibility with Flutter SDK versions

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_barcode_scanner: ^2.0.0


  http: ^1.2.2
  provider: ^6.0.0
  image_picker_web: ^2.1.0
  cached_network_image: ^3.2.0
  flutter_dotenv: ^5.0.2
  firebase_core: ^3.9.0
  flutter_svg: ^2.0.16
  image: ^4.0.15
  # Make sure the other Firebase dependencies are compatible with the new version
  firebase_auth_web: ^5.13.5
  firebase_auth: ^5.3.4
  firebase_database: ^11.2.0 # For Realtime Database
    # OR

  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7
  shared_preferences: ^2.0.17








dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/






