// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChYHMGA-Qz2eD9zR2Mf1E3ELfw9Do11kc',
    appId: '1:979546677280:web:16f33722234598d0f39c45',
    messagingSenderId: '979546677280',
    projectId: 'waste2worth-df0ec',
    authDomain: 'waste2worth-df0ec.firebaseapp.com',
    storageBucket: 'waste2worth-df0ec.firebasestorage.app',
    measurementId: 'G-4K1PZPC907',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWNSZA9EZw-fTTvwol3DlBy6TW8W4BRD0',
    appId: '1:979546677280:android:97099c2117686cf6f39c45',
    messagingSenderId: '979546677280',
    projectId: 'waste2worth-df0ec',
    storageBucket: 'waste2worth-df0ec.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaj8QhTdbfAcx03WauRvi5o95K9Nd6x-k',
    appId: '1:979546677280:ios:4c325255984f3402f39c45',
    messagingSenderId: '979546677280',
    projectId: 'waste2worth-df0ec',
    storageBucket: 'waste2worth-df0ec.firebasestorage.app',
    iosBundleId: 'com.example.waste2worth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaj8QhTdbfAcx03WauRvi5o95K9Nd6x-k',
    appId: '1:979546677280:ios:4c325255984f3402f39c45',
    messagingSenderId: '979546677280',
    projectId: 'waste2worth-df0ec',
    storageBucket: 'waste2worth-df0ec.firebasestorage.app',
    iosBundleId: 'com.example.waste2worth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChYHMGA-Qz2eD9zR2Mf1E3ELfw9Do11kc',
    appId: '1:979546677280:web:5164c31cb89e2cf9f39c45',
    messagingSenderId: '979546677280',
    projectId: 'waste2worth-df0ec',
    authDomain: 'waste2worth-df0ec.firebaseapp.com',
    storageBucket: 'waste2worth-df0ec.firebasestorage.app',
    measurementId: 'G-NWQVYN8MVB',
  );
}
